### ISSUE TITLE
bug: node 13 cannot use modules that have `module: true` set in package.json

### ISSUE THREAD

**Issue by bfla** [buccaneerai/bottlenose#37]
For some reason the Lerna monorepo does not work with node 13 if the package.json sets the flag `"type": "module"`...  Everything works fine in node 12.  This will need to be resolved so that all the development environment can run on node 13 and the modules can run on node 13!

**Comment by bfla** [comment]
`yarn test` fails when using node v13:
```bash
BriMac2:bottlenose bfla$ yarn test
yarn run v1.21.1
$ lerna run test --since
lerna notice cli v3.20.2
lerna notice filter changed since ""
lerna info Assuming all packages changed
lerna info Executing command in 7 packages: "npm run test"
lerna ERR! npm run test exited 1 in '@bottlenose/rxs3'
lerna ERR! npm run test stdout:

> @bottlenose/rxs3@0.2.1-beta.2 test /Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/packages/rxs3
> mocha --exit ./src/**/*.test.js ./src/*.test.js


lerna ERR! npm run test stderr:
/Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/pirates/lib/index.js:1
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/packages/rxs3/src/internals/completeUpload.test.js
require() of ES modules is not supported.
require() of /Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/packages/rxs3/src/internals/completeUpload.test.js from /Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/mocha/lib/mocha.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename completeUpload.test.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/packages/rxs3/package.json.

    at Module._extensions..js (internal/modules/cjs/loader.js:1160:13)
    at Object.newLoader [as .js] (/Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/pirates/lib/index.js:104:7)
    at /Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/mocha/lib/mocha.js:308:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/mocha/lib/mocha.js:305:14)
    at Mocha.run (/Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/mocha/lib/mocha.js:846:10)
    at Object.exports.singleRun (/Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/mocha/lib/cli/run-helpers.js:143:13)
    at Object.exports.handler (/Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/mocha/lib/cli/run.js:305:3)
    at Object.runCommand (/Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/Users/bfla/Documents/dev/buccaneer/opensource/bottlenose/node_modules/mocha/lib/cli/cli.js:73:11)
    at Generator.next (<anonymous>)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bottlenose/rxs3@0.2.1-beta.2 test: `mocha --exit ./src/**/*.test.js ./src/*.test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @bottlenose/rxs3@0.2.1-beta.2 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bfla/.npm/_logs/2020-02-04T19_49_04_213Z-debug.log

lerna ERR! npm run test exited 1 in '@bottlenose/rxs3'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bfla** [comment]
👍 Resolved
